### PR TITLE
Compatible to macOS

### PR DESCRIPTION
**Pull request by ykzts**
Fix https://github.com/tootsuite/mastodon/pull/2949#issuecomment-300260804

### CODE REVIEW

**Review by akihikodaki — CHANGES_REQUESTED** [review]
Hard-coding `FFI::Platform.mac?` and `bundle` does not look good.
I have opened #2. Can you review it?

**Comment by ykzts** [comment]
It does not matter on platforms other than macOS. It is not necessary to use values other than FFI.

**Comment by akihikodaki** [comment]
@ykzts The problem is FFI uses values irrelevant from native extensions; `FFI.map_library_name` is inteded to be compatible with libraries installed to the system.
Though it matters only for macOS for now, another platform may have different values for the two variables in future since the intensions of `FFI.map_library_name` and `RbConfig::CONFIG["DLEXT"]` are different. `RbConfig::CONFIG["DLEXT"]` sounds more _correct_ or something sort of, considering that.

**Comment by ykzts** [comment]
FFI is not intended to load an extension library of Ruby which builds by running `gem build`. This is the distortion that is occurring for that. Originally it should be implemented using `ruby.h` without using FFI.

My patch is the method used in `cld 2` gem. Temporarily use such a solution, eventually remove FFI.

**Comment by akihikodaki** [comment]
@ykzts The decision to use FFI is a different issue. Consider how we could deal with the distortion in this issue.
For your information, I decided to use FFI because I was convinced with https://github.com/ffi/ffi/wiki/why-use-ffi. Open another issue if you are against with that.

**Comment by ykzts** [comment]
What is written on the wiki does not take into consideration what is built from extconf.rb.

**Comment by akihikodaki** [comment]
> An FFI extension is multi-platform and multi-implementation
> An FFI extension works without changes on Ruby, JRuby, and any other Ruby VM that supports FFI.

This applies also for embedded extensions.

**Comment by ykzts** [comment]
I do not know how to write better than cdaee7f.

"ibcld3." Is hard-coded. I do not know the merit of using constants only for suffix.

**Comment by akihikodaki** [comment]
@ykzts The name of `libcld3` is not dependent on `mkmf`, but written in `extconf.rb`. It is safe to assume.
```Ruby
create_makefile("libcld3")
```
https://github.com/akihikodaki/cld3-ruby/commit/a82866fee388c4e076f827b6aeb7e3716eaee011#diff-008b2ea0e48987eb07538f63cb0739d2R49

**Comment by ykzts** [comment]
This is your library. If you do it your way, you are OK.

**Comment by akihikodaki** [comment]
Thank you for your pull request and discussion anyway. That helps to understand the issue of FFI better.

**Pull request closed without merging**
